#ifndef StTRIGGERS_H
#define StTRIGGERS_H

// see prescale.cxx
enum trgNumbers{BHT0BBCMB,BHT0BBCMB2,BHT0VPDMB5,BHT1BBCMB,BHT1BBCMB2,BHT1VPDMB30,BHT1VPDMB30nobsmd,BHT2BBCMB,BHT2BBCMB2,BBCMB,BBCMB2};

#endif
